fix(localization): Word & grammar adjustment
stegripe/rawon pull request #497
Opened 2021-10-01 11:51 UTC by KurokuTetsuya

2021-10-01 11:52 UTC, KurokuTetsuya commented
@mzrtamp if you want to improve word, grammar  and markdown, please commit to this PR

2021-10-01 11:57 UTC, Mednoob requested changes

2021-10-01 11:57 UTC, Mednoob commented on lang/id.json
> +				"slashDescription": "Nama commanperintahd untuk melihat informasi tentang perintah tertentu",
typo?

2021-10-02 11:49 UTC, mzrtamp commented
> @mzrtamp if you want to improve word, grammar and markdown, please commit to this PR

Ok

2021-10-02 12:01 UTC, mzrtamp reviewed
Let me propose 'em

2021-10-02 12:35 UTC, mzrtamp approved these changes
Good to go

2021-10-02 12:40 UTC, Mednoob approved these changes

2021-10-02 13:12 UTC, mzrtamp approved these changes
That's all, maybe?

2021-10-02 13:52 UTC, merged